"""Step 1 of the pipeline: raw CSV -> clean, audited 15-min OHLC parquet.

    python scripts/01_prepare_data.py

Writes:
    data/interim/nifty50_train.parquet
    data/interim/nifty50_test.parquet
    reports/01_data_quality.md
    reports/figures/01_price_coverage.png
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src import config
from src.data.loader import assert_no_leakage, clean, load_raw


def plot_coverage(train: pd.DataFrame, test: pd.DataFrame, out: Path) -> None:
    fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True,
                             gridspec_kw={"height_ratios": [3, 1]})

    axes[0].plot(train["timestamp"], train["close"], lw=0.5,
                 color="#2b6cb0", label=f"Train ({len(train):,} bars)")
    axes[0].plot(test["timestamp"], test["close"], lw=0.5,
                 color="#c05621", label=f"Test ({len(test):,} bars)")
    axes[0].axvline(test["timestamp"].iloc[0], color="k", ls="--", lw=1)
    axes[0].set_ylabel("Nifty 50 close")
    axes[0].set_title("Step 1 — cleaned 15-minute coverage")
    axes[0].legend(loc="upper left")
    axes[0].grid(alpha=0.25)

    both = pd.concat([train, test])
    per_day = both.groupby("session_date").size()
    per_day.index = pd.to_datetime(per_day.index)
    axes[1].plot(per_day.index, per_day.values, lw=0.6, color="#4a5568")
    axes[1].axhline(config.BARS_PER_SESSION, color="#38a169", ls="--", lw=1,
                    label=f"{config.BARS_PER_SESSION} bars/session")
    axes[1].set_ylabel("bars/session")
    axes[1].legend(loc="lower left")
    axes[1].grid(alpha=0.25)

    fig.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=130)
    plt.close(fig)


def main() -> None:
    config.INTERIM_DIR.mkdir(parents=True, exist_ok=True)
    config.REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    frames, reports = {}, []
    for split, path in (("train", config.RAW_TRAIN_CSV), ("test", config.RAW_TEST_CSV)):
        raw = load_raw(path)
        df, rep = clean(raw, split)
        frames[split] = df
        reports.append(rep)

        out = config.INTERIM_DIR / f"nifty50_{split}.parquet"
        df.to_parquet(out, index=False)
        print(f"{split:5s}  {rep.rows_in:>7,} -> {rep.rows_out:>7,} bars   "
              f"{rep.first_ts.date()} .. {rep.last_ts.date()}   -> {out.name}")

    assert_no_leakage(frames["train"], frames["test"])
    print("leakage check: test starts strictly after train ends  [OK]")

    fig_path = config.REPORTS_DIR / "figures" / "01_price_coverage.png"
    plot_coverage(frames["train"], frames["test"], fig_path)

    md = [
        "# Step 1 — Data Quality Report",
        "",
        "Generated by `scripts/01_prepare_data.py`. Source: `Nifty50_train.csv`, "
        "`Nifty50_test.csv` (NSE Nifty 50 index, 15-minute bars).",
        "",
        *[r.to_text() + "\n" for r in reports],
        "## Split integrity",
        "",
        f"- Train ends **{reports[0].last_ts}**, test starts **{reports[1].first_ts}** "
        "— strictly chronological, zero overlapping timestamps.",
        "",
        f"![coverage](figures/{fig_path.name})",
    ]
    report_path = config.REPORTS_DIR / "01_data_quality.md"
    report_path.write_text("\n".join(md), encoding="utf-8")
    print(f"report -> {report_path.relative_to(config.PROJECT_ROOT)}")
    print(f"figure -> {fig_path.relative_to(config.PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
